confirmed to work correctly.

diff --git a/kubetest b/kubetest
--- a/kubetest
+++ b/kubetest
@@ -7,22 +7,32 @@ VERSION="v0.01"
 #############################
 PROVIDER=kind
 #############################
+KIND_CLUSTER_NAME=${KIND_CLUSTER_NAME:-kubetest}
+#############################
 
 dir=$(cd $(dirname ${BASH_SOURCE:-$0}); pwd)
 
 
 usage() {
     echo "Deployment tool for various versions of kubernetes environment"
-    echo "Usage: $PROGNAME [OPTIONS] <kubernetes-version>"
     echo ""
-    echo "<kubernetes-version>: Enter kubernetes version [v1.18.2, v1.17, v1.16, v1.15, v1.14, v1.13, v1.12, v1.11]"
+    echo " Find more information at: https://github.com/k-shino/kubetest/blob/master/README.md"
+    echo ""
+    echo "Usage: $PROGNAME <command> [OPTIONS]"
+    echo ""
+    echo "Commands:"
+    echo ""
+    echo "  deploy <kubernetes-version>: deploy kubernetes cluster"
+    echo "    <kubernetes-version>: Enter kubernetes version [v1.18.2, v1.17, v1.16, v1.15, v1.14, v1.13, v1.12, v1.11]"
+    echo "  delete: delete kubernetes cluster"
+    echo "  configure: set current context to kubectl"
     echo ""
     echo "Options:"
     echo "  -p, --provider : select provider [kind(default)]"
+    echo "  -v, --verbose : verbose output"
     echo "  -h, --help"
     echo "      --version"
     echo ""
-    echo "Find more information at: https://github.com/k-shino/kubetest/blob/master/README.md"
     exit 1
 }
 
@@ -39,6 +49,7 @@ do
             ;;
         '-v'|'--verbose' )
             DEBUG=true
+            shift 1
             ;;
         '-p'|'--provider' )
             if [[ -z "$2" ]] || [[ "$2" =~ ^-+ ]]; then
@@ -66,8 +77,6 @@ do
     esac
 done
 
-echo "param: ${param[0]} ${param[1]}"
-
 if [[ -z "${param[0]}" ]]; then
     echo "$PROGNAME: too few arguments" 1>&2
     echo "Try '$PROGNAME --help' for more information." 1>&2
@@ -75,38 +84,58 @@ if [[ -z "${param[0]}" ]]; then
 fi
 
 CMD=${param[0]}
-PARAM=${param[1]}
 
 if [ $DEBUG ] ; then
-    echo "CMD: $CMD"
-    echo "PARAM: $PARAM"
+    echo "[DEBUG] Following parameters are specified."
+    echo "  - CMD: $CMD"
 fi
+
+i=0
+for e in ${param[@]}; do
+    eval PARAM${i}=${e}
+    if [ $DEBUG ] && [ $i -ne 0 ]; then
+        echo "  - PARAM${i}: ${e}"
+    fi
+    let i++
+done
+
+unset PARAM0
 
 case "$CMD" in
 
     'deploy' )
 
-        if [[ -z "${PARAM}" ]]; then
+        if [[ -z "${PARAM1}" ]]; then
             echo "$PROGNAME deploy: too few arguments" 1>&2
             echo "Try '$PROGNAME --help' for more information." 1>&2
             exit 1
         fi
         if [ "$PROVIDER" = "kind" ]; then
-            if [ ! -d ${dir}/kind/$PARAM ]; then
+            if [ ! -d ${dir}/kind/$PARAM1 ]; then
                 echo "[ERROR] Unsupported kubernetes version is specified."
                 exit 1
             fi
-            kustomize build ${dir}/kind/$PARAM | yq delete - metadata | kind create cluster --config -
+            kustomize build ${dir}/kind/$PARAM1 | yq delete - metadata | kind create cluster --config - --name ${KIND_CLUSTER_NAME}
         else
             echo "PROVIDER error"
             exit 1
         fi
         ;;
     'configure' )
-        kubectl cluster-info --context kind-kind
+        if [ "$PROVIDER" = "kind" ]; then
+            kubectl cluster-info --context kind-${KIND_CLUSTER_NAME}
+        else
+            echo "PROVIDER error"
+            exit 1
+        fi
         ;;
     'delete' )
-        kind delete cluster
+        if [ "$PROVIDER" = "kind" ]; then
+            kind delete cluster --name ${KIND_CLUSTER_NAME}
+        else
+            echo "PROVIDER error"
+            exit 1
+        fi
         ;;
     *)
         echo "command error"
